runtime: python38
entrypoint: streamlit run app.py

env_variables:
  BUCKET_NAME: music-gen-bucket


automatic_scaling:
  min_instances: 1
  max_instances: 50

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 32

handlers:
- url: /.*
  script: auto
